apiVersion: v1
kind: Service
metadata:
  name: chibest-api
  namespace: chibest
  labels:
    app: chibest-api
spec:
  selector:
    app: chibest-api
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080


