apiVersion: v1
kind: Service
metadata:
  name: chibest-postgres
  namespace: chibest
  labels:
    app: chibest-postgres
spec:
  type: ClusterIP
  selector:
    app: chibest-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432


