apiVersion: v1
kind: PersistentVolume
metadata:
  name: chibest-postgres-pv
  labels:
    app: chibest-postgres
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-local
  hostPath:
    path: /var/lib/chibest/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chibest-postgres-pvc
  namespace: chibest
  labels:
    app: chibest-postgres
spec:
  storageClassName: postgres-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


