apiVersion: v1
kind: Secret
metadata:
  name: chibest-secrets
  namespace: chibest
type: Opaque
stringData:
  POSTGRES_USER: chibest
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: chibest
  DB_PG_CONNECTION_STRING: Host=chibest-postgres;Port=5432;Database=chibest;Username=chibest;Password=change-me;Pooling=true;Maximum Pool Size=50;Timeout=15
  Jwt_Key: LocalDevJwtKey_ChangeMe_32CharsMinimum!
  Jwt_Issuer: Chibest.Api
  Jwt_Audience: Chibest.Client


